### ISSUE TITLE
Consider how to safely implement rewrite_sync and has_https_sync

### ISSUE THREAD

**Issue by mcatanzaro** [grindhold/libhttpseverywhere#29]
Iterating the default main context could cause applications to break in unexpected ways, since they regularly assume sources they create won't dispatch until they return to the main loop. Creating our own main loop and iterating it breaks that assumption and is likely to cause unexpected application misbehavior. (Sorry for not noticing this when I first wrote the code.) We need to create our own main context in `rewrite_sync` and `has_https_sync`, and set it as the thread default.

But if we do that, then initialization can never complete.

Honestly, this is becoming such a mess, I don't know how to fix it and am starting to think it may be a mistake to provide async variants of these functions at all. Applications can simply not call them before initialization completes if they don't want to block.

**Comment by mcatanzaro** [comment]
(Tips here: https://developer.gnome.org/programming-guidelines/stable/main-contexts.html.en#using-gmaincontext-in-a-library)

**Comment by grindhold** [comment]
after giving it some thought and looking at the code base, i came to the conclusion that 
it's best to agree with you. better have a maintainable library than a cluttered library. so let's
use async only if the method really takes long to execute like update and init. methods
like has_https and rewrite execute in an instant and already made sure that they can't
be executed when the lib is not ready to do so.

my planned measure of actions looks like the following:

a) not merging the cancellable_rewrite branch
b) identifying commits that should be reverted in order to make https_everywhere and
   rewrite synchronous again.
c) reverting and doing some testing

with this we should have a working release by monday.

**Comment by mcatanzaro** [comment]
OK. It's probably right; we can always add async methods in the future if someone wants them and if we can figure out a nice way to implement. Sorry for starting this huge rabbit-hole of async rewrite().

(a) obviously doesn't require any work. I'll try to do (b) and (c) soon (hopefully today).

**Comment by grindhold** [comment]
@mcatanzaro oh i already began with it and pushed. --winter-- release is coming.

**Comment by mcatanzaro** [comment]
@grindhold looks good, this is solved

**Comment by mcatanzaro** [comment]
Actually can we go back to the version that blocks until init has completed? That's nicer for Epiphany and you left all the infrastructure for it.

**Comment by mcatanzaro** [comment]
Nope, too hard!
